<?php
if (!defined('IN_FINECMS')) exit();

/**
 * 用户权限配置信息
 */
return array (
  1 => 
  array (
    0 => 'index',
    1 => 'auth',
    2 => 'category',
    3 => 'content',
    4 => 'model',
    5 => 'user',
    6 => 'position',
    7 => 'linkage',
    8 => 'plugin',
    9 => 'attachment',
    10 => 'relatedlink',
    11 => 'block',
    12 => 'member',
    13 => 'theme',
    14 => 'html',
    15 => 'form',
    16 => 'tag',
    17 => 'ip',
    18 => 'site',
    19 => 'navbar',
  ),
  2 => 
  array (
    0 => 'index-index',
    1 => 'index-config',
    2 => 'index-cache',
    3 => 'index-log',
    4 => 'index-clearlog',
    5 => 'index-updatemap',
    6 => 'site-config',
    7 => 'auth-index',
    8 => 'auth-add',
    9 => 'auth-edit',
    10 => 'auth-del',
    11 => 'auth-list',
    12 => 'auth-cache',
    13 => 'user-index',
    14 => 'user-add',
    15 => 'user-edit',
    16 => 'user-del',
    17 => 'model-index',
    18 => 'model-add',
    19 => 'model-edit',
    20 => 'model-del',
    21 => 'model-import',
    22 => 'model-export',
    23 => 'model-cdisabled',
    24 => 'model-fields',
    25 => 'model-addfield',
    26 => 'model-editfield',
    27 => 'model-delfield',
    28 => 'model-disable',
    29 => 'model-cache',
    30 => 'category-index',
    31 => 'category-add',
    32 => 'category-edit',
    33 => 'category-del',
    34 => 'category-cache',
    35 => 'content-index',
    36 => 'content-add',
    37 => 'content-del',
    38 => 'content-updateurl',
    39 => 'position-index',
    40 => 'position-add',
    41 => 'position-edit',
    42 => 'position-del',
    43 => 'position-list',
    44 => 'position-adddata',
    45 => 'position-editdata',
    46 => 'position-deldata',
    47 => 'position-cache',
    48 => 'plugin-index',
    49 => 'plugin-set',
    50 => 'plugin-disable',
    51 => 'plugin-del',
    52 => 'plugin-add',
    53 => 'attachment-index',
    54 => 'attachment-del',
    55 => 'relatedlink-index',
    56 => 'relatedlink-add',
    57 => 'relatedlink-edit',
    58 => 'relatedlink-del',
    59 => 'relatedlink-import',
    60 => 'html-index',
    61 => 'html-category',
    62 => 'html-clear',
    63 => 'form-index',
    64 => 'form-list',
    65 => 'form-add',
    66 => 'form-edit',
    67 => 'form-del',
    68 => 'navbar-index',
    69 => 'navbar-add',
    70 => 'navbar-edit',
    71 => 'navbar-del',
    72 => 'navbar-list',
    73 => 'navbar-adddata',
    74 => 'navbar-editdata',
    75 => 'navbar-deldata',
    76 => 'navbar-cache',
  ),
  3 => 
  array (
    0 => 'index-config',
    1 => 'auth-add',
    2 => 'auth-edit',
    3 => 'auth-set',
    4 => 'form-list',
  ),
);